# Generated by Django 5.0.3 on 2024-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('reminder_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
